# Generated by Django 4.1.3 on 2023-03-04 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_remove_bid_highest_bid_bid_bid_price_bid_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid_price',
            field=models.IntegerField(default=0),
        ),
    ]
