# Generated by Django 4.1.3 on 2023-03-06 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_catagory_alter_listing_catagory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='min_bid',
            field=models.IntegerField(default=0),
        ),
    ]
