# Generated by Django 4.1.3 on 2023-03-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_listing_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='min_bid',
            field=models.IntegerField(),
        ),
    ]
