# Generated by Django 4.1.3 on 2023-03-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_listing_min_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='BidActive',
            field=models.BooleanField(default=True),
        ),
    ]
